version: "3.8"

services:
  app:
    image: "url-shortener:latest"
    container_name: "url-shortener"
    restart: always
    depends_on:
      - db
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    command: sh ./scripts/start-prod.sh
    env_file:
      - .env

  db:
    image: "postgres:14-alpine"
    container_name: "url-shortener-db"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:


networks:
  default:
    name: "nginx-proxy"
